Name:		htmlscript
Version:	1.0.1
Release:	2
Summary:	Tool for displaying HTML generated by scripts
License:	GPLv3
Group:		System/Configuration/Other
URL:		http://github.com/OpenMandrivaSoftware/htmlscript
Source0:	https://github.com/OpenMandrivaSoftware/htmlscript/archive/%{version}.tar.gz
BuildRequires:	cmake
BuildRequires:	ninja
BuildRequires:	qmake5
BuildRequires:	cmake(Qt5Core)
BuildRequires:	cmake(Qt5Gui)
BuildRequires:	cmake(Qt5Widgets)
BuildRequires:	cmake(Qt5WebEngineWidgets)

%description
A tool for displaying HTML generated by scripts.

It is used by oma-welcome and oma-control-center.

%prep
%setup -q
%autopatch -p1

%build
%cmake_qt5 -G Ninja
%ninja

%install
%ninja_install -C build

%files
%doc LICENSE
%{_bindir}/htmlscript
