%bcond_with qt5

Name:		htmlscript
Version:	1.1.0
Release:	2
Summary:	Tool for displaying HTML generated by scripts
License:	GPLv3
Group:		System/Configuration/Other
URL:		http://github.com/OpenMandrivaSoftware/htmlscript
Source0:	https://github.com/OpenMandrivaSoftware/htmlscript/archive/%{version}.tar.gz
BuildRequires:	cmake
BuildRequires:	ninja
%if %{with qt5}
BuildRequires:	qmake5
BuildRequires:	cmake(Qt5)
BuildRequires:	cmake(Qt5Core)
BuildRequires:	cmake(Qt5Gui)
BuildRequires:	cmake(Qt5Widgets)
BuildRequires:	cmake(Qt5WebEngineWidgets)
%else
BuildRequires:	cmake(Qt6)
BuildRequires:	cmake(Qt6Core)
BuildRequires:	cmake(Qt6DBus)
BuildRequires:	cmake(Qt6Gui)
BuildRequires:	cmake(Qt6QuickWidgets)
BuildRequires:	cmake(Qt6Widgets)
BuildRequires:	cmake(Qt6WebEngineWidgets)
%endif

%description
A tool for displaying HTML generated by scripts.

It is used by oma-welcome and oma-control-center.

%prep
%autosetup -p1
%cmake \
%if %{with qt5}
	-DQT_VERSION:STRING="5" \
%endif
	-G Ninja

%build
%ninja_build -C build

%install
%ninja_install -C build

%files
%doc LICENSE
%{_bindir}/htmlscript
